pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'RelativityMC'
            url = 'https://repo.codemc.io/repository/relativitymc/'
        }
    }
}

rootProject.name = 'chrispymod'

include('common')
include('fabric')
//include('forge')
include('neoforge')